name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 'latest'
    - name: Install Clojure deps
      run: clojure -M:deps
    - name: Install Node deps
      run: npm install
    - name: Run tests
      run: clojure -M:test
      